# Generated by Django 4.2.1 on 2023-05-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0002_department_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
