# Generated by Django 4.2.1 on 2023-05-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_department_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='admin',
        ),
    ]
