# Generated by Django 4.2 on 2023-04-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_customer_city_alter_customer_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='rental_rate',
            name='vehicle_size',
        ),
        migrations.RemoveField(
            model_name='rental_rate',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='size',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='Rental_Rate',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle_size',
        ),
        migrations.DeleteModel(
            name='Vehicle_type',
        ),
    ]
