# Generated by Django 4.2 on 2023-04-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_alter_vehicle_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.customer'),
        ),
    ]
