# Generated by Django 4.2 on 2023-05-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
