# Generated by Django 4.2 on 2023-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_gif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(related_name='Categories', to='add_gif.gif'),
        ),
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
